# Generated by Marten 0.2.0 on 2023-02-17 21:01:26 -05:00

class Migration::Main::V202302172101261 < Marten::Migration
  def plan
    create_table :main_article do
      column :id, :big_int, primary_key: true, auto: true
      column :title, :string, max_size: 255
      column :content, :text
    end
  end
end
