# Generated by Marten 0.2.0 on 2023-02-19 21:01:16 -05:00

class Migration::Main::V202302192101161 < Marten::Migration
  depends_on :main, "202302172101261_create_main_article_table"

  def plan
    create_table :main_comment do
      column :id, :big_int, primary_key: true, auto: true
      column :message, :string, max_size: 255
      column :article_id, :reference, to_table: :main_article, to_column: :id
    end
  end
end
